// Actions constants:
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const CLEAR_MOVIE_DETAIL = "CLEAR_MOVIE_DETAIL";
export const GET_SERIE_DETAIL = "GET_SERIE_DETAIL";
export const CLEAR_SERIE_DETAIL = "CLEAR_SERIE_DETAIL";
export const GET_SEASON_DETAIL = "GET_SEASON_DETAIL";